# Documentation page information
site_name: SparkFun USB-C Host Shield Hookup Guide
site_description: A hookup guide for the USB-C Host Shield
site_url: https://sparkfun.github.io/SparkFun_USB-C_Host_Shield
site_author: SparkFun Electronics

repo_url: https://github.com/sparkfun/SparkFun_USB-C_Host_Shield
repo_name: sparkfun/SparkFun_USB-C_Host_Shield

copyright: Copyright 2022 SparkFun Electronics (6333 Dry Creek Parkway, Niwot, Colorado 80503)


# Configuration for webpage theme
theme:
  name: material
  logo: assets/img/sfe_logo_sm.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs

  # Adds light/dark theme to webpage
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: grey
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      accent: red
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: red
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode    

  # Configures icons of callout boxes
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  # Adds PDF icon to download hookup guide
  custom_dir: docs/overrides


# Included MkDocs plugins
# Add the installation of any new plugins to the ./github/workflows/mkdocs.yml file also
plugins:
  - search
  - monorepo
  - with-pdf:
      cover_logo: img/sfe_logo_sm.png
      exclude_pages: [ "print_pdf" ]
      output_path: board_files/product_manual.pdf


# Included Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # base_path: ['./docs']
      url_download: true
      url_max_size: 0
      url_timeout: 0
      url_request_headers: {}
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - tables
  - admonition
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons


# Configures social icons in footer
extra:
  social:
    - icon: sfe_logo
      link: https://www.sparkfun.com/products/21247
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/sparkfun
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sparkfun
    - icon: fontawesome/brands/github
      link: https://www.github.com/sparkfun
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SparkFun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sparkfun
    - icon: fontawesome/regular/file-pdf
      link: ../board_files/product_manual.pdf
# Configures styling for PDF rendering and webpage layout
extra_css:
  - overrides/extra.css


# Configures webpage navigation
nav:
  - Product Description: index.md
  - Hookup Guide:
    # - Introduction: index.md
    - Getting Started: hookup_guide/getting_started.md
    - Hardware Overview: hookup_guide/hardware_overview.md
    - Hardware Assembly: hookup_guide/hardware_assembly.md
    - Software Overview: hookup_guide/software_overview.md
    - Troubleshooting Tips: hookup_guide/troubleshooting_tips.md
    - Download Hookup Guide: hookup_guide/print_pdf.md
  - Arduino Examples:
    - Example 1: arduino_examples/example1.md
    - Example 2: arduino_examples/example2.md
    - Example 3: arduino_examples/example3.md
  - Product Resources:
    - Board Files: resources/board_files.md
    - Hardware Datasheets: resources/component_documentation.md
    - Troubleshooting Tips: hookup_guide/troubleshooting_tips.md
    - Maxim Integrated's Resources: resources/resources-manufacturer.md
    - SparkFun's Resources: resources/resources-sparkfun.md
  - Issues/Pull Requests:
    - Issues: github/file_issue.md
    - Contribute: github/contribute.md
  # - Print: print.md