name: Run mkdocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-monorepo-plugin mkdocs-print-site-plugin
      # - run: apt install pango1.0-tools
      - run: mkdocs gh-deploy --force
